
service: lambda-image-resizer

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  environment: ${file(./env/${opt:stage}.yml)}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${file(./env/${opt:stage}.yml):S3_BUCKET_NAME}/*"

package:
  artifact: dst.zip

functions:
  getImage:
    handler: handlers.getImage
    events:
      - http:
          path: getImage
          method: get

  uploadImage:
    handler: handlers.uploadImage
    events:
      - http:
          path: uploadImage
          method: post
          cors: true

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "${file(./env/${opt:stage}.yml):DYNAMO_DB_TABLE_NAME}"
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: version
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: version
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DynamoDbTable
      Properties:
        PolicyName: AmazonDynamoDBFullAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: [
                "dynamodb:*"
              ]
              Resource: "arn:aws:dynamodb:*:*:table/${file(./env/${opt:stage}.yml):DYNAMO_DB_TABLE_NAME}"
        Roles:
          - Ref: IamRoleLambdaExecution
