
service: lambda-image-resizer

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1

package:
  artifact: dst.zip

functions:
  getImage:
    handler: handlers.getImage
    events:
      - http:
          path: getImage
          method: get

  uploadImage:
    handler: handlers.uploadImage
    events:
      - http:
          path: uploadImage
          method: post
          cors: true
